### ISSUE TITLE
[08/22 meeting] Harsha to present branching and pull requests!

### ISSUE THREAD

**Issue by ybvau** [opendigital/opendigital-org#15]
For GitHub etiquette, Harsha will be presenting branching and pull requests.

**Comment by harshpavuluri** [comment]
https://purdue0.sharepoint.com/:v:/s/TECH-RCODI/ERzfCuPA9bpEqIA6__u9qc8B_2ypF8MtUnQizWhjmTnxaQ?e=uudHhh

Recording for branches and pull requests added here. Should also be found through the office 365 Sharepoint as well

**Comment by jialincheoh** [comment]
Link to recording -> https://purdue0.sharepoint.com/sites/TECH-RCODI/Shared%20Documents/General/Recordings/RCODI%20team%20meeting-20220823_082439-Meeting%20Recording.mp4?web=1

**Comment by ybvau** [comment]
Presentation was given!!
