### ISSUE TITLE
Add Brittney into Tower Access

### ISSUE THREAD

**Issue by jialincheoh** [opendigital/opendigital-org#17]
1. create access for Brittney to tower
2. create a txt file with the instructions for Brittany
3. share it with secure data transmission (not email). 

To add users

```
sudo adduser username
```

To create users with admin rights 

```
sudo usermod -aG sudo username
```

Verify if user is added 

```
$ cat /etc/passwd
$ grep '^brittney' /etc/passwd
```

Relevant links: 
https://linuxize.com/post/how-to-create-users-in-linux-using-the-useradd-command/

**Comment by sbrunswi** [comment]
Here this is the instructions we want to send: 
# NEW SERVER USER SSH INSTRUCTIONS

## HOW TO CREATE A NEW SSH KEY

```sh
ssh-keygen -t rsa -b 4096 -o -a 100 -C <user>@<hostname>
```

## YOUR SSH KEY USERNAME

```sh
sbrunswi
```

## YOUR SSH KEY PASSWORD

```sh
2EbYaMRhMV8gQLVr
```

Note: Store this somewhere safe and don\'t rely on this
file as a permanent solution.

## ADD THE SSH-KEY TO YOUR SSH-AGENT KEYRING

\*\*THIS STEP IS REQUIRED**

```sh
ssh-add /<path>/<to>/<keyfile>
```

```sh
> Enter passphrase for id_username_hostname: __

Identity added: id_username_hostname (username@hostname)
```

## UPDATE YOUR SSH CONFIG

You can also set these parameters using commandline flags

(refer to ssh manual `man ssh` for instructions)

```sh
# ~/.ssh/config
Host ironhub
  Hostname 142.93.60.97
  User <username>
  IdentityFile /home/<username>/.ssh/id_<username>_<hostname>
```

## CONNECT TO THE SERVER

```sh
ssh ironhub
```

**Comment by jialincheoh** [comment]
reference article to add users for key based access -> https://thucnc.medium.com/how-to-create-a-sudo-user-on-ubuntu-and-allow-ssh-login-20e28065d9ff

**Comment by jialincheoh** [comment]
Name: Brittany Green 
Email: brittany.green.1@louisville.edu
Phone: (502)852-4787

**Comment by jialincheoh** [comment]
Create new user account 

```
$ sudo adduser newuser
```

Switch to the new user account 

```
$ su - newuser
```

Add public key to allow remote SSH login for the new user

1. Switch to the new user account

```
$ su - newuser
```

**Comment by sbrunswi** [comment]
@jialincheoh  - This is taken care off! However, we need a new issue on documentation of admin process!
