### ISSUE TITLE
Mail Chimp Demo & Documentation & Guide

### ISSUE THREAD

**Issue by crashidian** [opendigital/opendigital-org#27]
Manthan to give demonstration of mail chimp to the RCODI team. Additionally, he is to request a PW and identify where the PW goes to, and ensure that the PW goes to an account that most people have access to.  He is to also document to the RCODI team a d make a guide.

**Comment by crashidian** [comment]
https://github.com/opendigital/opendigital-org/blob/master/guides/keepass/Intro_to_Keepass_for_Shared_Passwords.md

**Comment by twinblade02** [comment]
Marking closed
