### ISSUE TITLE
Create a Readme file for the organizational wiki page 

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/opendigital-org#3]
Problem: Currently, there is no readme file. So the public is not clear what that repo is about. 

Solution: Can we find a way to write a brief paragraph about what RCODI is and what we do? The repo contains information about the RCODI team and provides team members access to information that can be publically shared.

**Comment by annahein9** [comment]
I have uploaded readme file. It is based off of the summary on the website, but I have made a few updates.
